In [31]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier

In [2]:
df = pd.read_csv('creditcard.csv')

In [8]:
df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [7]:
df.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
284802,172786.0,-11.881118,10.071785,-9.834783,-2.066656,-5.364473,-2.606837,-4.918215,7.305334,1.914428,...,0.213454,0.111864,1.014480,-0.509348,1.436807,0.250034,0.943651,0.823731,0.77,0
284803,172787.0,-0.732789,-0.055080,2.035030,-0.738589,0.868229,1.058415,0.024330,0.294869,0.584800,...,0.214205,0.924384,0.012463,-1.016226,-0.606624,-0.395255,0.068472,-0.053527,24.79,0
284804,172788.0,1.919565,-0.301254,-3.249640,-0.557828,2.630515,3.031260,-0.296827,0.708417,0.432454,...,0.232045,0.578229,-0.037501,0.640134,0.265745,-0.087371,0.004455,-0.026561,67.88,0
284805,172788.0,-0.240440,0.530483,0.702510,0.689799,-0.377961,0.623708,-0.686180,0.679145,0.392087,...,0.265245,0.800049,-0.163298,0.123205,-0.569159,0.546668,0.108821,0.104533,10.00,0
284806,172792.0,-0.533413,-0.189733,0.703337,-0.506271,-0.012546,-0.649617,1.577006,-0.414650,0.486180,...,0.261057,0.643078,0.376777,0.008797,-0.473649,-0.818267,-0.002415,0.013649,217.00,0

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB

In [10]:
df.isnull().sum().sum()

0

In [13]:
# Distribution of legit and fraud transactions
df['Class'].value_counts()

Class
0    284315
1       492
Name: count, dtype: int64

In [14]:
legit = df[df.Class == 0]
fraud = df[df.Class == 1]

In [15]:
print(legit.shape)
print(fraud.shape)

(284315, 31)
(492, 31)

In [16]:
legit.Amount.describe()

count    284315.000000
mean         88.291022
std         250.105092
min           0.000000
25%           5.650000
50%          22.000000
75%          77.050000
max       25691.160000
Name: Amount, dtype: float64

In [17]:
fraud.Amount.describe()

count     492.000000
mean      122.211321
std       256.683288
min         0.000000
25%         1.000000
50%         9.250000
75%       105.890000
max      2125.870000
Name: Amount, dtype: float64

In [18]:
df.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,94838.202258,0.008258,-0.006271,0.012171,-0.007860,0.005453,0.002419,0.009637,-0.000987,0.004467,...,-0.000644,-0.001235,-0.000024,0.000070,0.000182,-0.000072,-0.000089,-0.000295,-0.000131,88.291022
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

In [19]:
# Under sampling
legit_sample = legit.sample(n=492)

In [20]:
new_dataset = pd.concat([legit_sample,fraud],axis = 0)

In [21]:
new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
238345,149632.0,0.137799,0.993757,-0.960342,-1.066165,1.959637,0.988969,0.725453,0.331710,-0.450641,...,-0.305021,-0.875249,0.195582,3.033323,-0.352669,-0.020787,0.204860,0.099406,5.49,0
121233,76119.0,1.206166,-0.583114,-1.844353,-1.851829,1.991457,2.892687,-0.197347,0.635566,1.040121,...,-0.020831,-0.141435,-0.304574,1.047320,1.088065,-0.543705,0.022517,0.019459,87.11,0
64477,51160.0,-0.473404,1.811874,-0.384438,0.935675,1.500809,-1.092740,1.181286,-0.012862,-1.274874,...,-0.033762,-0.078557,-0.320337,-0.112531,0.253458,-0.335575,0.101158,0.127393,0.89,0
119950,75646.0,-1.111727,-0.249867,1.676378,-0.073293,-1.279935,0.407448,-0.446938,0.707439,-1.603441,...,0.052446,0.322632,0.195673,0.231472,-0.264044,0.561298,-0.016859,0.011233,129.38,0
194595,130671.0,-0.796943,0.217795,-0.043020,-0.661375,2.074270,-0.728531,0.557709,-0.168210,-0.130548,...,-0.429286,-0.937133,-0.268545,0.207809,0.016223,0.163336,0.001573,-0.230315,11.99,0

In [22]:
new_dataset['Class'].value_counts()

Class
0    492
1    492
Name: count, dtype: int64

In [23]:
# The mean of df and new_dataset is similar so the nature of data set is not changed
df.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,94838.202258,0.008258,-0.006271,0.012171,-0.007860,0.005453,0.002419,0.009637,-0.000987,0.004467,...,-0.000644,-0.001235,-0.000024,0.000070,0.000182,-0.000072,-0.000089,-0.000295,-0.000131,88.291022
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

In [24]:
X = new_dataset.drop(columns = 'Class',axis = 1)
y = new_dataset['Class']

In [25]:
X

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
238345,149632.0,0.137799,0.993757,-0.960342,-1.066165,1.959637,0.988969,0.725453,0.331710,-0.450641,...,0.187793,-0.305021,-0.875249,0.195582,3.033323,-0.352669,-0.020787,0.204860,0.099406,5.49
121233,76119.0,1.206166,-0.583114,-1.844353,-1.851829,1.991457,2.892687,-0.197347,0.635566,1.040121,...,0.151936,-0.020831,-0.141435,-0.304574,1.047320,1.088065,-0.543705,0.022517,0.019459,87.11
64477,51160.0,-0.473404,1.811874,-0.384438,0.935675,1.500809,-1.092740,1.181286,-0.012862,-1.274874,...,0.002688,-0.033762,-0.078557,-0.320337,-0.112531,0.253458,-0.335575,0.101158,0.127393,0.89
119950,75646.0,-1.111727,-0.249867,1.676378,-0.073293,-1.279935,0.407448,-0.446938,0.707439,-1.603441,...,-0.146440,0.052446,0.322632,0.195673,0.231472,-0.264044,0.561298,-0.016859,0.011233,129.38
194595,130671.0,-0.796943,0.217795,-0.043020,-0.661375,2.074270,-0.728531,0.557709,-0.168210,-0.130548,...,0.009827,-0.429286,-0.937133,-0.268545,0.207809,0.016223,0.163336,0.001573,-0.230315,11.99
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
279863,169142.0,-1.927883,1.125653,-4.518331,1.749293,-1.566487,-2.010494,-0.882850,0.697211,-2.064945,...,1.252967,0.778584,-0.319189,0.639419,-0.294885,0.537503,0.788395,0.292680,0.147968,390.00
280143,169347.0,1.378559,1.289381,-5.004247,1.411850,0.442581,-1.326536,-1.413170,0.248525,-1.127396,...,0.226138,0.370612,0.028234,-0.145640,-0.081049,0.521875,0.739467,0.389152,0.186637,0.76
280149,169351.0,-0.676143,1.126366,-2.213700,0.468308,-1.120541,-0.003346,-2.234739,1.210158,-0.652250,...,0.247968,0.751826,0.834108,0.190944,0.032070,-0.739695,0.471111,0.385107,0.194361,77.89
281144,169966.0,-3.113832,0.585864,-5.399730,1.817092,-0.840618,-2.943548,-2.208002,1.058733,-1.632333,...,0.306271,0.583276,-0.269209,-0.456108,-0.183659,-0.328168,0.606116,0.884876,-0.253700,245.00
281674,170348.0,1.991976,0.158476,-2.583441,0.408670,1.151147,-0.096695,0.223050,-0.068384,0.577829,...,-0.017652,-0.164350,-0.295135,-0.072173,-0.450261,0.313267,-0.289617,0.002988,-0.015309,42.53

In [26]:
y

238345    0
121233    0
64477     0
119950    0
194595    0
         ..
279863    1
280143    1
280149    1
281144    1
281674    1
Name: Class, Length: 984, dtype: int64

In [27]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,stratify=y,random_state=42)

In [28]:
X_train

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
171908,120872.0,0.691635,1.966528,-0.375985,4.927262,1.174774,-0.264597,0.935216,-0.252159,-1.673563,...,0.362686,-0.464228,-0.939966,0.124137,-0.325160,-0.742227,0.022233,0.145085,-0.140083,4.37
152569,97411.0,1.856231,-0.475122,0.619854,0.805989,-1.494838,-0.970680,-0.916187,-0.125151,2.600503,...,-0.187416,-0.039640,0.221691,0.415628,0.899723,-0.750669,0.382195,-0.043061,-0.029834,39.00
56703,47545.0,1.176716,0.557091,-0.490800,0.756424,0.249192,-0.781871,0.228750,-0.040840,-0.432111,...,-0.102772,-0.062166,-0.128168,-0.040176,0.110040,0.437891,0.368809,-0.018287,0.031173,0.76
150684,93888.0,-10.040631,6.139183,-12.972972,7.740555,-8.684705,-3.837429,-11.907702,5.833273,-5.731054,...,-0.082275,2.823431,1.153005,-0.567343,0.843012,0.549938,0.113892,-0.307375,0.061631,1.00
6882,8808.0,-4.617217,1.695694,-3.114372,4.328199,-1.873257,-0.989908,-4.577265,0.472216,0.472017,...,-0.039046,0.481830,0.146023,0.117039,-0.217565,-0.138776,-0.424453,-1.002041,0.890780,1.10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39183,39729.0,-0.964567,-1.643541,-0.187727,1.158253,-2.458336,0.852222,2.785163,-0.303609,0.940006,...,1.784449,0.447180,0.536204,1.634061,0.203839,0.218749,-0.221886,-0.308555,-0.164500,776.83
78141,57388.0,-0.962495,1.542840,0.927665,-0.024360,-0.377487,-0.807104,0.321176,0.465325,-0.719731,...,0.165329,-0.182529,-0.533750,0.062793,0.492532,-0.125612,0.047485,0.230449,0.085951,13.99
143335,85285.0,-6.713407,3.921104,-9.746678,5.148263,-5.151563,-2.099389,-5.937767,3.578780,-4.684952,...,0.135711,0.954272,-0.451086,0.127214,-0.339450,0.394096,1.075295,1.649906,-0.394905,252.92
42370,41076.0,-0.534515,1.100385,1.148152,-0.135998,0.333331,-0.483862,0.606589,0.030388,-0.639259,...,0.142676,-0.215405,-0.588765,-0.006048,-0.041041,-0.124009,0.063178,0.117299,0.077014,0.89
17317,28625.0,-27.848181,15.598193,-28.923756,6.418442,-20.346228,-4.828202,-19.210896,18.329406,-3.668735,...,1.697856,1.802149,-2.062934,-1.269843,0.165409,1.999499,-0.211059,1.324809,0.388090,99.99

In [29]:
X_test

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
230076,146179.0,-0.067672,4.251181,-6.540388,7.283657,0.513541,-2.635066,-1.865911,0.780272,-3.868248,...,0.519404,0.415437,-0.469938,0.007128,-0.388147,-0.493398,0.466468,0.566370,0.262990,0.77
262826,160665.0,-0.417340,4.700055,-7.521767,7.671884,0.260821,-2.646693,-2.854432,0.958783,-4.588536,...,0.832035,0.622200,-0.437708,-0.090358,-0.742802,-0.312361,0.502575,0.821390,0.372379,0.77
131536,79637.0,-0.298718,1.193962,1.092855,-0.074642,0.382486,-0.657296,0.758355,-0.093082,-0.503709,...,0.187935,-0.289354,-0.708789,-0.098364,-0.177456,-0.057201,0.102028,0.252080,0.094747,0.89
30314,35866.0,-2.044489,3.368306,-3.937111,5.623120,-3.079232,-1.253474,-5.778880,1.707428,-4.467103,...,1.112028,1.483594,0.834311,-0.148486,0.001669,-0.038996,0.389526,1.300236,0.549940,7.61
71750,54429.0,1.168393,-0.036816,0.623328,0.842022,-0.443954,-0.097255,-0.199612,0.022244,0.568145,...,-0.115133,-0.072902,0.077099,-0.049309,0.155690,0.490029,0.438373,0.004473,0.010774,12.36
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
276959,167381.0,-0.398190,0.624641,1.614437,-0.559491,0.129688,0.245691,0.245899,0.293188,0.072077,...,-0.071358,-0.080883,-0.257814,-0.058824,0.707662,-0.369136,-0.583863,0.147447,0.142832,2.99
6472,7740.0,1.023874,2.001485,-4.769752,3.819195,-1.271754,-1.734662,-3.059245,0.889805,0.415382,...,0.204138,0.343283,-0.054196,0.709654,-0.372216,-2.032068,0.366778,0.395171,0.020206,1.00
21462,31682.0,-0.786325,1.161564,1.343958,0.540191,0.884900,1.475210,0.062238,-1.506147,-0.289531,...,-0.209596,1.329486,-0.633525,-0.091592,-1.154923,-0.086413,-0.422892,0.115251,-0.096199,8.03
52466,45463.0,-1.476893,2.122314,-1.229470,1.201849,-0.343264,-1.317704,-1.528142,-0.620953,-1.213040,...,0.276893,1.186036,-0.040215,-0.238930,0.110144,0.045418,-0.569232,0.481019,-0.047555,1.00
121219,76114.0,-0.592331,1.505973,1.138544,1.549268,1.147410,0.757913,0.515083,-0.736434,-1.400958,...,-0.179499,0.914159,0.264824,-0.181390,-0.935439,-0.168177,0.056500,0.198547,0.152822,0.00

In [30]:
y_train

171908    0
152569    0
56703     1
150684    1
6882      1
         ..
39183     1
78141     0
143335    1
42370     0
17317     1
Name: Class, Length: 787, dtype: int64

In [39]:
models = {
    "Logistic Regression": LogisticRegression(),
    "Random Forest": RandomForestClassifier(),
    "Decision Tree": DecisionTreeClassifier()
}
for i in range(len(list(models))):
    model = list(models.values())[i]
    model.fit(X_train,y_train)
    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)

    model_train_accuracy = accuracy_score(y_train_pred,y_train)
    model_test_accuracy = accuracy_score(y_test_pred,y_test)

    print(list(models.keys())[i])
    print('Model Accuracy on Train Data:',model_train_accuracy)
    print('Model Accuracy on Test Data:',model_test_accuracy)
    print('=='*30)
    print('\n')

C:\Users\ANAND REDDY\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Logistic Regression
Model Accuracy on Train Data: 0.9364675984752223
Model Accuracy on Test Data: 0.9695431472081218
============================================================


Random Forest
Model Accuracy on Train Data: 1.0
Model Accuracy on Test Data: 0.9746192893401016
============================================================


Decision Tree
Model Accuracy on Train Data: 1.0
Model Accuracy on Test Data: 0.9390862944162437
============================================================

In [41]:
# Hyperparameter Tuning
rf_params = {"max_depth": [5,8,15,None,10],
            "max_features":[5,7,"auto",8],
            "min_samples_split":[2,8,15,20],
            "n_estimators":[100,200,500,1000]}
lg_params = {
    'solver': ['newton-cg', 'lbfgs', 'sag', 'saga'],
    'penalty': ['l1', 'l2'],
    'C': [0.1, 1, 10],
    'max_iter': [100, 500, 1000]
}

In [42]:
random_cv = [
    ("RF",RandomForestClassifier(),rf_params),
    ("LR",LogisticRegression(),lg_params)
]

In [45]:
import warnings
warnings.simplefilter('ignore')

In [46]:
from sklearn.model_selection import RandomizedSearchCV
model_params = {}
for name,model,params in random_cv:
    random = RandomizedSearchCV(estimator=model,
                                param_distributions=params,
                                verbose = 2,
                                n_jobs= -1,
                               n_iter=50,
                               )
    random.fit(X_train,y_train)
    model_params[name] = random.best_params_
for model_name in model_params:
    print(f"--------------------Best Paarams for {model_name}-------------------")
    print(model_params[model_name])

Fitting 5 folds for each of 50 candidates, totalling 250 fits
Fitting 5 folds for each of 50 candidates, totalling 250 fits
--------------------Best Paarams for RF-------------------
{'n_estimators': 200, 'min_samples_split': 8, 'max_features': 5, 'max_depth': None}
--------------------Best Paarams for LR-------------------
{'solver': 'lbfgs', 'penalty': 'l2', 'max_iter': 500, 'C': 0.1}

In [49]:
models = {
    "Logistic Regression": LogisticRegression(solver= 'lbfgs', penalty= 'l2', max_iter= 500, C= 0.1),
    "Random Forest": RandomForestClassifier(n_estimators= 200, min_samples_split= 8, max_features= 5, max_depth= None)
}
for i in range(len(list(models))):
    model = list(models.values())[i]
    model.fit(X_train,y_train)
    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)

    model_train_accuracy = accuracy_score(y_train_pred,y_train)
    model_test_accuracy = accuracy_score(y_test_pred,y_test)

    print(list(models.keys())[i])
    print('Model Accuracy on Train Data:',model_train_accuracy)
    print('Model Accuracy on Test Data:',model_test_accuracy)
    print('=='*30)
    print('\n')

Logistic Regression
Model Accuracy on Train Data: 0.9466327827191868
Model Accuracy on Test Data: 0.9695431472081218
============================================================


Random Forest
Model Accuracy on Train Data: 0.9936467598475223
Model Accuracy on Test Data: 0.9695431472081218
============================================================